Vagrant.configure("2") do |config|
  # Define the SSH public key for the user 'mg0050'
  ssh_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPqxEMsu0Nmi+B9yf6WdkkxWIUKzgc5VZUM4URMiZH0cawIHFd1SHiptcOaNm6DZPKF+haguMMSew/HPhiF2bFHTba3YYsAify2KuN1m2hUkaWGb+OSxPsp2d/FCh4wyMY9YMXnM+NDFx54meDLJwjfLdeRTlcZ/1YOIEpiMC6VSAmHG0c97H5yxfcS2mu8y7+mRUtIIFJbx7OFDe9v22+KXSEoChscQv57ORfAW/KkT1SZICTi4I0sHob5GcTcsO9jfj5BvknV3Xng14Jkz26SeYA16VkvMjdPofa/HgHGfLHkwZWjJBROkY3Hk0qbg02SAnvlhUjdxi1xZ1tDUVv mg0050@L00026.fritz.box"

  # Define the root password and user password
  root_password = ENV['ROOT_PW']

  # VM rh1
  config.vm.define "rh1" do |rh1|
    rh1.vm.box = "generic/rhel9"
    rh1.vm.network "public_network", ip: "192.168.64.101"
    rh1.vm.hostname = "rh1"

    # Set up provisioning to configure root password, create new user, and set SSH key
    rh1.vm.provision "shell", inline: <<-SHELL
      # Set root password
      echo "root:#{root_password}" | sudo chpasswd

      # Create new user mg0050
      sudo useradd -m -s /bin/bash mg0050

      # Set up SSH access for mg0050
      sudo mkdir -p /home/mg0050/.ssh
      echo "#{ssh_key}" | sudo tee /home/mg0050/.ssh/authorized_keys
      sudo chown -R mg0050:mg0050 /home/mg0050/.ssh
      sudo chmod 700 /home/mg0050/.ssh
      sudo chmod 600 /home/mg0050/.ssh/authorized_keys
    SHELL
  end

  # VM rh2
  config.vm.define "rh2" do |rh2|
    rh2.vm.box = "generic/rhel9"
    rh2.vm.network "public_network", ip: "192.168.64.102"
    rh2.vm.hostname = "rh2"

    # Set up provisioning to configure root password, create new user, and set SSH key
    rh2.vm.provision "shell", inline: <<-SHELL
      # Set root password
      echo "root:#{root_password}" | sudo chpasswd

      # Create new user mg0050
      sudo useradd -m -s /bin/bash mg0050

      # Set up SSH access for mg0050
      sudo mkdir -p /home/mg0050/.ssh
      echo "#{ssh_key}" | sudo tee /home/mg0050/.ssh/authorized_keys
      sudo chown -R mg0050:mg0050 /home/mg0050/.ssh
      sudo chmod 700 /home/mg0050/.ssh
      sudo chmod 600 /home/mg0050/.ssh/authorized_keys
    SHELL
  end
end

