---
apiVersion: v1
kind: Deployment
metadata:
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mg0050
  template:
    metadata:
      labels:
        app: mg0050
  spec:  
    containers:
      - name: webserver1
        image: nginx:latest
        ports:
          - containerPort: 80    
