---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advpool
  namespace: metallb-system
spec:
  ipAddressPools:
  - ip-pool-ingress
  - ip-pool-services
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool-ingress
  namespace: metallb-system
spec:
  addresses:
  - 192.168.65.240 - 192.168.65.244
  avoidBuggyIPs: true
  serviceAllocation:
    namespaces:
      - ingress-nginx
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool-services
  namespace: metallb-system
spec:
  addresses:
  - 192.168.65.245 - 192.168.65.249
  avoidBuggyIPs: true