- name: Create local bkp folder
  gather_facts: false
  hosts:
    - localhost
  tasks:
    - ansible.builtin.file:
        path: /Users/mg0050/git/playground/ex294/backup
        state: directory
        mode: 0755    

- name: Create archive of /etc
  hosts:
    - all
  become: true
  tasks:
    - name: Create folder
      ansible.builtin.file:
        path: /backup
        state: directory
        mode: 0755
        owner: automation
        group: automation
        recurse: true
    - name: Create archive
      ansible.builtin.archive:
        path: /etc
        dest: /backup/configuration.gz
        format: gz
        owner: automation
        group: automation
        mode: 0660
    - name: Fetch files
      ansible.builtin.fetch:
        src: /backup/configuration.gz
        dest: /Users/mg0050/git/playground/ex294/backup/{{ inventory_hostname }}-configuration.gz
        flat: yes
