---
all:
  children:
    infra:
      hosts:
        u01:
          ansible_host: 192.168.64.17
    kube:
      hosts:
        kube01:
          ansible_host: 192.168.64.27
        kube02:
          ansible_host: 192.168.64.28
        kube03:
          ansible_host: 192.168.64.29
    test:
      hosts:
        u02:
          ansible_host: 192.168.64.18
        u03:
          ansible_host: 192.168.64.19
    ex294:
      hosts:
        ex294_01:
          ansible_host: 192.168.64.31
        ex294_02:
          ansible_host: 192.168.64.32
        ex294_03:
          ansible_host: 192.168.64.33
    office:
      hosts:
        eins:
          ansible_host: 192.168.64.3
        zwei:
          ansible_host: 192.168.64.4
        drei:
          ansible_host: 192.168.64.5
        vier:
          ansible_host: 192.168.64.6
    other:
      hosts:
        r01:
          ansible_host: 192.168.64.35
        r02:
          ansible_host: 192.168.64.36
        r03:
          ansible_host: 192.168.64.37
        r04:
          ansible_host: 192.168.64.38
