---
all:
  children:
    infra:
      hosts:
        u01:
          ansible_host: 192.168.64.17
    kube:
      children:
        kube_master:
          hosts:
            ks8-m1:
              ansible_host: 192.168.64.27
        kube_worker:
          hosts:
            k8s-n1:
              ansible_host: 192.168.64.28
            k8s-n2: 
              ansible_host: 192.168.64.29
      vars:
        ansible_python_interpreter: /usr/bin/python3.12

    test:
      hosts:
        u02:
          ansible_host: 192.168.64.18
        u03:
          ansible_host: 192.168.64.19
    ex294:
      hosts:
        ex294_01:
          ansible_host: 192.168.64.31
        ex294_02:
          ansible_host: 192.168.64.32
        ex294_03:
          ansible_host: 192.168.64.33
    office:
      hosts:
        eins:
          ansible_host: 192.168.64.3
        zwei:
          ansible_host: 192.168.64.4
        drei:
          ansible_host: 192.168.64.5
        vier:
          ansible_host: 192.168.64.6
    other:
      hosts:
        r01:
          ansible_host: 192.168.64.35
        r02:
          ansible_host: 192.168.64.36
        r03:
          ansible_host: 192.168.64.37
        r04:
          ansible_host: 192.168.64.38
