apiVersion: v1
kind: Service
metadata:
  name: webservice
spec:
  type: LoadBalancer
  selector:
    key1: "label1" # ist das Label aus der Deployment YML
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 80
