apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    key1: "label1" # zum mappen des Services
spec:
  containers:
    - name: webserver1
      image: nginx:latest
      ports:
        - containerPort: 80
