---
services:
  pihole:
   container_name: pihole
   image: pihole/pihole:2025.05.1
   ports:
     - "53:53/udp"
     - "53:53/tcp"
     - "80:80/tcp"
     - "443:443/tcp"
   environment:
     TZ: "Europe/Berlin"
     FTLCONF_dns_listeningMode: "all"
     FTLCONF_webserver_api_password: "WpYGTQ_2V*ostzPx"
     FTLCONF_dns_upstreams: 8.8.8.8;8.8.4.4
   volumes:
     - "./etc-pihole:/etc/pihole"
     - "./etc-dnsmasq.d:/etc/dnsmasq.d"
   restart: unless-stopped
