---
version: "3"
services:
  pihole:
   container_name: pihole
   image: pihole/pihole:2024.07.0
   ports:
     - "53:53/udp"
     - "53:53/tcp"
     - "67:67/udp"
     - "80:80/tcp"
   environment:
     TZ: "Europe/Berlin"
     WEBPASSWORD: "WpYGTQ_2V*ostzPx"
   volumes:
     - "./etc-pihole:/etc/pihole"
     - "./etc-dnsmasq.d:/etc/dnsmasq.d"
   cap_add:
     - NET_ADMIN
   restart: unless-stopped
