---
all:
  children:
    master:
      hosts:
        u01:
          ansible_host: 192.168.64.2
    worker:
      hosts:
        u02:
          ansible_host: 192.168.64.40
        u03:
          ansible_host: 192.168.64.41
