---
- name: All
  become: true
  hosts:
    - all
  tasks:
    - name: Ping
      ansible.builtin.ping:
    - name: Update APT Cache
      apt:
        update_cache: true
        autoclean: true
        autoremove: true
    - name: Install additional packages
      apt:
        name: "{{ apt_pkgs }}"
        state: present
    - name: Place resolv.conf
      ansible.builtin.template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644
    - name: Place sshd_config
      ansible.builtin.template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644
    - name: Restart ssh
      ansible.builtin.service:
        name: ssh
        state: restarted
