---
- name: Install and setup haproxy
  hosts:
    - infra
  gather_facts: False
  become: True
  tasks:
    - name: Install haproxy
      apt:
        update_cache: True
        autoclean: True
        autoremove: True
        name: haproxy
        state: present
    - name: Create HAProxy configuration file
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
    - name: Enable HAProxy service
      systemd:
        name: haproxy
        enabled: yes
        state: started
    - name: Ensure HAProxy is started
      service:
        name: haproxy
        state: started
