---
- name: Setup K3s
  become: true
  hosts:
    - all

  tasks:
    - name: Install K3s on master node
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -s - server --cluster-init --node-ip "{{ ansible_default_ipv4.address }}" --flannel-iface "{{ ansible_default_ipv4.interface }}"
    - name: Read token on master node
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token
    - name: Show token
      debug:
        msg: "{{ k3s_token['content'] | b64decode }}"
    - name: Get file with K3s token
      ansible.builtin.fetch:
        src: /var/lib/rancher/k3s/server/node-token
        dest: files/
        flat: true
