---
- name: Install Kubernetes
  become: true
  hosts:
    - kube

  handlers:
    - name: Handlers
      ansible.builtin.import_tasks: handlers/main.yml

  tasks:
    - name: Common OS preparation
      ansible.builtin.include_tasks: tasks/common.yml

    - name: Configure kernel settings
      ansible.builtin.include_tasks: tasks/kernel.yml

    - name: Configure containerd
      ansible.builtin.include_tasks: tasks/containerd.yml

    - name: Install Kubernetes packages
      ansible.builtin.include_tasks: tasks/kubernetes-packages.yml
      tags:
        - prepare_k8s

    - name: Configure Kubernetes control plane
      ansible.builtin.include_tasks: tasks/control-plane.yml
      when: inventory_hostname in groups['kube_master']
      tags:
        - install_k8s

    - name: Join Kubernetes workers
      ansible.builtin.include_tasks: tasks/workers.yml
      when: inventory_hostname in groups['kube_worker']
      tags:
        - worker_k8s
