---
- name: Setup DNS
  become: true
  hosts:
    - infra
  gather_facts: true
  tasks:
    - name: Install neccessary packages
      apt:
        update_cache: true
        name: "{{ apt_pkgs }}"
        state: present
    - name: Place zone.{{domain_name}} in /etc/bind
      template:
        src: zone.j2
        dest: /etc/bind/zone.{{domain_name}}
        mode: 0644
        owner: root
        group: root
    - name: Place reverse.{{domain_name}} in /etc/bind
      template:
        src: reverse.j2
        dest: /etc/bind/reverse.{{domain_name}}
        mode: 0644
        owner: root
        group: root
    - name: Place named.conf in /etc/bind
      template:
        src: named.conf.j2
        dest: /etc/bind/named.conf.local
        mode: 0644
        owner: root
        group: root
    - name: Place resolv.conf in /etc/
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        mode: 0644
        owner: root
        group: root
    - name: Restart bind9 service
      ansible.builtin.service:
        name: bind9
        state: restarted
