---
- name: Shutdown
  hosts:
    - all
  become: true
  ignore_unreachable: true
  tasks:
    - name: Ensure your user is allowed to do this shit
      ansible.builtin.template:
        src: sudo.j2
        dest: /etc/sudoers.d/{{ ansible_env.USER }}
        owner: root
        group: root
        mode: "0440"
    - name: Shut down the servers
      ansible.builtin.shell: |
        /sbin/shutdown -h now
      register: shut_out
      ignore_errors: true
      changed_when: shut_out.rc == 0
