---
- name: RHEL VM herunterfahren
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: System herunterfahren
      ansible.builtin.command:
        cmd: shutdown -h now
      async: 1
      poll: 0
      failed_when: false

    - name: Playbook erfolgreich beenden
      ansible.builtin.meta: end_host
