apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: tt3
spec:
  storageClassName: local-path
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /nfs
    server: 192.168.65.17
