apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'metallb'
spec:
  project: default
  source:
    repoURL: 'git@github.com:demxtsk5/playground.git'
    path: k_tests/metallb
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
