---
# Deaktiviere Swap sofort, da Kubernetes dies für das Ressourcenmanagement erfordert
- name: Disable swap
  ansible.builtin.command:
    cmd: swapoff -a
  when: ansible_facts["swaptotal_mb"] > 0
  changed_when: ansible_facts["swaptotal_mb"] > 0

# Kommentiere Swap-Einträge in /etc/fstab aus, damit Swap nach einem Reboot deaktiviert bleibt
- name: Disable swap in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s.*)$'
    replace: '# \1'

# Begrenze die maximale Größe der systemd Log-Dateien auf 200MB, um Speicherplatz zu sparen
- name: Limit systemd journal size
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?SystemMaxUse="
    line: "SystemMaxUse=200M"
  notify: Restart journald
