---
- name: Verzeichnis für APT-Keyrings erstellen
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Configure Kubernetes APT repository
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: [deb]
    uris: "https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/"
    suites: ["/"]
    components: []
    signed_by: "https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/Release.key"
    state: present
    install_python_debian: true

- name: Paket-Cache manuell aktualisieren
  ansible.builtin.apt:
    update_cache: true

- name: Install Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg
    - kubelet
    - kubeadm
    - kubectl

- name: Versionen von K8s-Paketen einfrieren (hold)
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl